### ISSUE TITLE
步骤都做完了，为什么没有效果呢？

### ISSUE THREAD

**Issue by justcodingnobb** [YouEclipse/waka-box-go#1]

**Comment by justcodingnobb** [comment]
panic: PATCH https://api.github.com/gists/xxx: 422 Validation Failed [{Resource:Gist Field:files Code:missing_field Message:}]
是因为 gist 文件的原因？

**Comment by zu1k** [comment]
第一次运行后，gist里面文件丢失，提示如下：

```
We couldn’t find that file to show.
```

后续运行异常退出

**Comment by YouEclipse** [comment]
`📊 Weekly development breakdown`  gist的文件名改成这个

**Comment by zu1k** [comment]
> `📊 Weekly development breakdown` gist的文件名改成这个

尝试过，运行后这个文件会被删除，然后后面运行就会出错了

**Comment by YouEclipse** [comment]
> > `📊 Weekly development breakdown` gist的文件名改成这个
> 
> 尝试过，运行后这个文件会被删除，然后后面运行就会出错了

你的wakatime账号是新建的吗?如果没有数据 文件会被清空

**Comment by zu1k** [comment]
> > > `📊 Weekly development breakdown` gist的文件名改成这个
> > 
> > 
> > 尝试过，运行后这个文件会被删除，然后后面运行就会出错了
> 
> 你的wakatime账号是新建的吗?如果没有数据 文件会被清空

的确是新建的，不过我刚刚安装idea插件了，能够在后台的dashboard看到一小部分数据了，不太清楚从api能不能获取到数据

**Comment by YouEclipse** [comment]
> > > > `📊 Weekly development breakdown` gist的文件名改成这个
> > > 
> > > 
> > > 尝试过，运行后这个文件会被删除，然后后面运行就会出错了
> > 
> > 
> > 你的wakatime账号是新建的吗?如果没有数据 文件会被清空
> 
> 的确是新建的，不过我刚刚安装idea插件了，能够在后台的dashboard看到一小部分数据了，不太清楚从api能不能获取到数据

可以明天再看看 具体wakatime怎么统计时间的 还无法确认

**Comment by zu1k** [comment]
输出了一下，的确是空数据，PR #3  防止自动删除gist里面创建好的文件

**Comment by zu1k** [comment]
今天能获取到数据，正常了

**Comment by YouEclipse** [comment]
> 今天能获取到数据，正常了

OK～ 感谢反馈
