### ISSUE TITLE
Update the profile README

### ISSUE THREAD

**Issue by YouEclipse** [YouEclipse/waka-box-go#14]
As Github has a new feature of profile README, maybe waka-box-go can support updating the stats to profile README.

on way to update  is adding a comment in the README and then update the comment area.
just like
```
<!--waka-box start -->
<!--waka-box end -->
```

**Comment by YouEclipse** [comment]
@AarynSmith  what do you think about?

**Comment by AarynSmith** [comment]
Sounds like a great idea to me.
