### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by banmajio** [YouEclipse/waka-box-go#2]
![image](https://user-images.githubusercontent.com/53471385/83997252-8d589900-a990-11ea-8033-1c9a50df8489.png)

acticon有个节点报错

https://github.com/banmajio/waka-box-go   大佬有空帮忙看下

**Comment by YouEclipse** [comment]
`📊 Weekly development breakdown`  你把gist的文件名改成`📊 Weekly development breakdown`

**Comment by banmajio** [comment]
![image](https://user-images.githubusercontent.com/53471385/84000008-7452e680-a996-11ea-899c-7f40559fe6aa.png)
是改成这样吗？  但还是报上面的错

**Comment by YouEclipse** [comment]
> ![image](https://user-images.githubusercontent.com/53471385/84000008-7452e680-a996-11ea-899c-7f40559fe6aa.png)
> 是改成这样吗？ 但还是报上面的错

emoji也要带上,你可以看下源码; 另外,要确保wakatime有数据;

**Comment by banmajio** [comment]
wakatime的数据在哪里可以看到啊？小白一个不是很懂！

**Comment by banmajio** [comment]
![image](https://user-images.githubusercontent.com/53471385/84013349-60fe4600-a9ab-11ea-8005-cf22d2e7182e.png)
现在没有报错了  但是依然没有效果。  wakatime的数据是在上图显示的吗？
有两个问题问一下大佬。
1.📊 Weekly development breakdown里面的内容是自动生成的？还是我需要往里面手动添加东西？
2.wakatime是要根据我的ide使用来搜集数据吗？也就是说我必须要在ide中安装这个插件？

**Comment by YouEclipse** [comment]
> ![image](https://user-images.githubusercontent.com/53471385/84013349-60fe4600-a9ab-11ea-8005-cf22d2e7182e.png)
> 
> 现在没有报错了  但是依然没有效果。  wakatime的数据是在上图显示的吗？
> 
> 有两个问题问一下大佬。
> 
> 1.📊 Weekly development breakdown里面的内容是自动生成的？还是我需要往里面手动添加东西？
> 
> 2.wakatime是要根据我的ide使用来搜集数据吗？也就是说我必须要在ide中安装这个插件？

- 内容是自动生成的
- 要使用这个插件

**Comment by banmajio** [comment]
wakatime有数据了，但是运行还是报错
![image](https://user-images.githubusercontent.com/53471385/84101800-65753e00-aa41-11ea-8feb-4f3b9ac6518d.png)

**Comment by yeung66** [comment]
> wakatime有数据了，但是运行还是报错
> ![image](https://user-images.githubusercontent.com/53471385/84101800-65753e00-aa41-11ea-8feb-4f3b9ac6518d.png)

这个是数据不够所以出错了
