### ISSUE TITLE
wont run

### ISSUE THREAD

**Issue by Milo123459** [YouEclipse/waka-box-go#21]
what I did: changed the cron to run every minute, what it doesn't do:
update the gist.
I also checked actions and workflows and there was nothing there for update gists..
if anyone can help, I would appreciate it

**Comment by YouEclipse** [comment]
Hi~  you can check the logs of the actions. 
https://github.com/Milo123459/waka-box-go/runs/930247499?check_suite_focus=true#step:4:16 

the log shows the  GIST_ID is invalid.
