### ISSUE TITLE
Is enabling Actions of the forked repository mandatory?

### ISSUE THREAD

**Issue by yihuajack** [YouEclipse/waka-box-go#25]
At first I failed to update my gist completing all the steps in README. Then I found a step "Open the 'Actions' tab of your fork and click the 'enable' button" in another box project's README (https://github.com/maxam2017/productive-box). I tried this step and successfully update my gist. Is enabling Actions of the forked repository mandatory? If so, I suggest add this step in README.

**Comment by YouEclipse** [comment]
not pretty sure,sometimes it works well after forked,but it's better to add this step in README. thanks for suggestion.
