### ISSUE TITLE
关于执行的时间周期

### ISSUE THREAD

**Issue by yeung66** [YouEclipse/waka-box-go#7]
我从原项目那里得知，wakaTime 的每周数据是按天来更新呢的，所以每小时执行的话其实也不会有更新 Gist 的显示（我当时看到 Github Action 执行了但是显示却没有更新数据,还以为是出什么问题了 😂 

所以感觉执行周期改成每天一次更好？

`cron: "0 0 * * *"`

**Comment by YouEclipse** [comment]
可以的，我当时用的默认的没有改

**Comment by YouEclipse** [comment]
你可以提个pr~
